write_data = input("Enter text to write to the file: ")
file = open('output.txt','w')
write_file = file.write(write_data)
file.close()
print("Data successfully written to output.txt.")

append_data = input("Enter additional text to append: ")
file = open('output.txt','a')
write_file = file.write("\n"+append_data)
file.close()
print("Data successfully appended.")

print("Final content of output.txt:")
file = open('output.txt','r')
read_file1 = file.readline()
read_file2 = file.readline()
print(read_file1, end = "")
print(read_file2)
file.close()